media:
  link: ${SHUFFLER_AVATAR_PATH:http://localhost/avatar/}

spring:
  datasource:
    hikari:
      schema: public
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${SHUFFLER_DB_HOST:localhost}:${SHUFFLER_DB_PORT:5432}/${SHUFFLER_DB_NAME:shuffler_local}${SHUFFLER_DB_URL_PARAMS:}
    username: ${SHUFFLER_DB_USER:local}
    password: ${SHUFFLER_DB_PASSWORD:root}

server:
  port: ${SHUFFLER_PORT:8800}
  forward-headers-strategy: native
  servlet:
    context-path: /api
    session:
      cookie:
        http-only: true
  tomcat:
    max-connections: 10000
    threads:
      max: 1000
      min-spare: 50
  cors.allowed:
    origins: ${CORS_ORIGINS:http://localhost:3000, https://www.shuffler.owl-tech.ru}
